### PR TITLE
set up api testing for the scripts instead of on app testing. You can…

### PR DESCRIPTION
**Pull request by JuiMin**
… now search your name with the API.

### CODE REVIEW

**Comment by n95pong** [comment]
I'll take a look at this when I get back

**Comment by JuiMin** [comment]
kkk.

reviews are like simple usually. For this one you can run npm start in the server and visit
localhost:3001. It has an example of the only script i put in.

generally you can take a look at the code itself too. If anything looks weird there you can request a change.

**Comment by n95pong** [comment]
rip npm start on my desktop

**Comment by JuiMin** [comment]
yeah...not sure what's going on with your desktop...

**Pull request merged**
